name: gogopher
services:
  gogopher:
    image: dbppgpmdtacr/gogopher:latest
    container_name: "gogopher"
    pull_policy: "always"
    volumes:
      # Mount the gopher root directory read-only.
      # Consider binding a host path for easier updates.

      - gopher-root:/gopher-root:ro

      # Consider binding these config files to host paths for easier updates
      # It is recommended to use read-only mode.

      #- ./firewall-config.json:/firewall-config.json:ro
      #- ./file-access-config.json:/file-access-config.json:ro
    environment:
      - TITLE=Wes C's Gopher Hole
      - HOSTNAME=localhost
      - HOST_BIND_IP=0.0.0.0
      - PORT=70
      - GOPHER_ROOT=/gopher-root
      - FIREWALL_CONFIG_FILE=firewall-config.json
      - FILE_ACCESS_CONFIG_FILE=file-access-config.json
      - REQUEST_TIMEOUT_SECONDS=30
      - REQUEST_MAXIMUM_BYTES=1024
    ports:
      - '70:70'
volumes:
  gopher-root:
