name: gogopher
services:
  gogopher:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "gogopher"
    volumes:
      - gopher-root:/gopher-root
    environment:
      - TITLE="Wes C's Gopher Server"
      - HOSTNAME=localhost
      - HOST_BIND_IP=0.0.0.0
      - PORT=70
      - GOPHER_ROOT=/gopher-root
      - FIREWALL_CONFIG_FILE=firewall-config.json
      - IDLE_TIMEOUT_SECONDS=10
      - READWRITE_TIMEOUT_SECONDS=30
    ports:
      - '70:70'
volumes:
  gopher-root:
    