name: gogopher
services:
  gogopher:
    image: dbppgpmdtacr/gogopher:latest
    container_name: "gogopher"
    volumes:
      # Mount the gopher root directory read-only.
      - gopher-root:/gopher-root:ro
      # Consider mounting the firewall config file for easier updates
      # If you do, it is recommended to use read-only mode
      #- ./firewall-config.json:/firewall-config.json:ro
    environment:
      - TITLE="Wes C's Gopher Server"
      - HOSTNAME=localhost
      - HOST_BIND_IP=0.0.0.0
      - PORT=70
      - GOPHER_ROOT=/gopher-root
      - FIREWALL_CONFIG_FILE=firewall-config.json
      - REQUEST_TIMEOUT_SECONDS=30
    ports:
      - '70:70'
volumes:
  gopher-root:
