print("This is an example of lua script sending dynamic content to the client")
print(context.Title)
print(context.HostName)
print(context.Port)
print(context.TLSEnabled)
print(context.TotalConnections)
print(context.Uptime)
print(context.OS)
print(context.Architecture)
print(context.GopherRoot)
local filename = context.GopherRoot .. "/$textfile.txt"
local content, err = read_file(filename)
assert(content, err)
print(content)